### ISSUE TITLE
Lab 04 / Practice 3 / Task 1 / Step 20 , Current directory is not correct.

### ISSUE THREAD

**Issue by wbpluto** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.zh-cn#1]
# Module: 04
#### Step: 20

Wrong: 将当前目录设置为“AdventureWorks”
Correct: 将当前目录设置为“AdventureWorks.Context”

![Lab04 - task02 - 2023-01-11 161635](https://user-images.githubusercontent.com/5191513/211850028-22b68024-322e-4e77-9806-a99d658b9d8d.jpg)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
